// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Service.DaataAccess.ServiceDomain.Interface;

namespace Service.DaataAccess.ServiceDomain.Models;

public partial class ODCContext : DbContext, IODCContextInterface
{
    private readonly string _connectionString;
    public ODCContext()
    {
    }

    public ODCContext(DbContextOptions<ODCContext> options)
        : base(options)
    {
    }

    public ODCContext(string connectionString)
    {
        this._connectionString = connectionString;
    }

    public virtual DbSet<AccountDetails> AccountDetails { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountDetails>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ContactNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}